# Generated by Django 5.2.3 on 2025-06-30 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mês')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receita')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Comissão')),
                ('new_clients', models.IntegerField(verbose_name='Novos Clientes')),
                ('churns', models.IntegerField(verbose_name='Cancelamentos (Churn)')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Squad')),
                ('active_clients', models.IntegerField(default=0, verbose_name='Clientes Ativos')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('store_name', models.CharField(max_length=200, unique=True, verbose_name='Nome da Loja')),
                ('seller_id', models.CharField(max_length=50, verbose_name='ID do Cliente')),
                ('seller_email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Cliente')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20)),
                ('contracted_plan', models.CharField(max_length=100, verbose_name='Plano Contratado')),
                ('plan_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Plano')),
                ('client_commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Comissão')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='Dados de Performance Mensal')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Rescisão do Contrato')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='manager.squad', verbose_name='Squad Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='SquadPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mês')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receita do Squad')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='manager.squad', verbose_name='Squad')),
            ],
            options={
                'ordering': ['month', 'squad'],
                'unique_together': {('squad', 'month')},
            },
        ),
    ]
