# Generated by Django 5.2.3 on 2025-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='seller_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Cliente'),
        ),
    ]
