# Generated by Django 5.2.3 on 2025-06-24 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Rescisão do Contrato'),
        ),
    ]
