# Generated by Django 5.2.3 on 2025-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_client_seller_email_alter_client_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='store_name',
            field=models.CharField(max_length=200, verbose_name='Nome da Loja'),
        ),
    ]
